# Generated by Django 2.1.7 on 2019-02-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='这个人很懒，什么都没有留下', max_length=300, verbose_name='个性签名'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(0, '男'), (1, '女')], default=0, max_length=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_pet',
            field=models.BooleanField(default=False, verbose_name='是否有宠物'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='married',
            field=models.BooleanField(default=False, verbose_name='婚姻状况'),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(default=0, verbose_name='收养个数'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='willing',
            field=models.BooleanField(default=False, verbose_name='收养意愿'),
        ),
    ]
