# Generated by Django 2.1.7 on 2019-03-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pet_info',
            fields=[
                ('pet_id', models.IntegerField(max_length=15, primary_key=True, serialize=False, verbose_name='宠物ID')),
                ('rescuer_id', models.IntegerField(max_length=15, verbose_name='救助者ID')),
                ('publisher_id', models.IntegerField(max_length=15, verbose_name='发布者ID')),
                ('pet_type', models.CharField(choices=[('1', 'Dog'), ('2', 'Cat')], max_length=1, verbose_name='动物类型')),
                ('pet_name', models.CharField(max_length=50, verbose_name='动物名称')),
                ('pet_age', models.IntegerField(max_length=2, verbose_name='动物年龄')),
                ('maturity_size', models.IntegerField(choices=[('0', 'Not Specified'), ('1', 'Small'), ('2', 'Medium'), ('3', 'Large'), ('4', 'Extra Large')], max_length=1, verbose_name='动物体型')),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Mixed, if profile represents group of pets')], max_length=1, verbose_name='动物性别')),
                ('fur_length', models.IntegerField(max_length=5, verbose_name='毛长')),
                ('vaccinated', models.BooleanField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'Not Sure')], max_length=1, verbose_name='是否接受疫苗')),
                ('dewormed', models.BooleanField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'Not Sure')], max_length=1, verbose_name='是否已除虫')),
                ('sterilized', models.BooleanField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'Not Sure')], max_length=1, verbose_name='是否已消毒')),
                ('health', models.CharField(choices=[('0', 'Not Specified'), ('1', 'Healthy'), ('2', 'Minor Injury'), ('3', 'Serious Injury')], max_length=1, verbose_name='健康程度')),
                ('quantity', models.IntegerField(max_length=3)),
                ('fee', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='收养费')),
                ('state', models.CharField(max_length=200, verbose_name='州位置')),
                ('video_amt', models.CharField(max_length=15, verbose_name='视频')),
                ('photo_amt', models.CharField(max_length=15, verbose_name='照片')),
                ('description', models.CharField(max_length=500, verbose_name='描述')),
                ('adoption_speed', models.IntegerField(max_length=3, verbose_name='被收养速率')),
            ],
        ),
    ]
