# Generated by Django 2.1.7 on 2019-03-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(default='发布者很懒，什么都没有说', max_length=3000, verbose_name='描述'),
        ),
    ]
