# Generated by Django 2.1.7 on 2019-03-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_info',
            name='publisher_id',
        ),
        migrations.RemoveField(
            model_name='pet_info',
            name='rescuer_id',
        ),
        migrations.AddField(
            model_name='pet_info',
            name='primary_breed',
            field=models.CharField(choices=[('Felinae', '短毛猫'), ('Persian', '波斯猫'), ('DragonLi', '狸花猫')], default='None', max_length=200, verbose_name='主要血统'),
        ),
        migrations.AddField(
            model_name='pet_info',
            name='primary_color',
            field=models.CharField(choices=[('B', 'Blue'), ('R', 'Red'), ('G', 'Green')], default=None, max_length=10, verbose_name='主要毛色'),
        ),
        migrations.AddField(
            model_name='pet_info',
            name='publisher_name',
            field=models.CharField(default=None, max_length=30, verbose_name='发布者姓名'),
        ),
        migrations.AddField(
            model_name='pet_info',
            name='rescuer_name',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='救助者姓名'),
        ),
        migrations.AddField(
            model_name='pet_info',
            name='secondary_breed',
            field=models.CharField(blank=True, choices=[('Felinae', '短毛猫'), ('Persian', '波斯猫'), ('DragonLi', '狸花猫')], default=None, max_length=200, verbose_name='次要血统'),
        ),
        migrations.AddField(
            model_name='pet_info',
            name='secondary_color1',
            field=models.CharField(blank=True, choices=[('B', 'Blue'), ('R', 'Red'), ('G', 'Green')], default=None, max_length=10, verbose_name='次要毛色1'),
        ),
        migrations.AddField(
            model_name='pet_info',
            name='secondary_color2',
            field=models.CharField(blank=True, choices=[('B', 'Blue'), ('R', 'Red'), ('G', 'Green')], default=None, max_length=10, verbose_name='次要毛色2'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='adoption_speed',
            field=models.IntegerField(blank=True, default=0, max_length=3, verbose_name='被收养速率'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='description',
            field=models.CharField(default='发布者很懒，什么都没有说', max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='dewormed',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Not Sure')], default=3, max_length=1, verbose_name='是否已除虫'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='fee',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, verbose_name='收养费'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='fur_length',
            field=models.IntegerField(blank=True, default=0, max_length=5, verbose_name='毛长'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Mixed, if profile represents group of pets')], default='3', max_length=1, verbose_name='动物性别'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='health',
            field=models.CharField(choices=[('0', 'Not Specified'), ('1', 'Healthy'), ('2', 'Minor Injury'), ('3', 'Serious Injury')], default='3', max_length=1, verbose_name='健康程度'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='maturity_size',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Specified'), (1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'Extra Large')], default=0, max_length=1, verbose_name='动物体型'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='pet_age',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='动物年龄'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='pet_name',
            field=models.CharField(default=None, max_length=50, verbose_name='动物名称'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='pet_type',
            field=models.CharField(choices=[('1', 'Dog'), ('2', 'Cat')], default=None, max_length=1, verbose_name='动物类型'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='photo_amt',
            field=models.CharField(blank=True, default='None', max_length=15, verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, max_length=3, verbose_name='体重'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='state',
            field=models.CharField(blank=True, default='None', max_length=200, verbose_name='州位置'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='sterilized',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Not Sure')], default=3, max_length=1, verbose_name='是否已消毒'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='vaccinated',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Not Sure')], default=3, max_length=1, verbose_name='是否接受疫苗'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='video_amt',
            field=models.CharField(blank=True, default='None', max_length=15, verbose_name='视频'),
        ),
    ]
