# Generated by Django 2.1.7 on 2019-03-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20190311_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='publisher_name',
            field=models.CharField(default=None, max_length=50, verbose_name='发布者姓名'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='rescuer_name',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='救助者姓名'),
        ),
    ]
