# Generated by Django 2.1.7 on 2019-03-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20190302_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_info',
            name='pet_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='宠物ID'),
        ),
    ]
