# Generated by Django 2.1.7 on 2019-03-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20190302_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_info',
            name='adoption_speed',
            field=models.IntegerField(blank=True, default=0, verbose_name='被收养速率'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='dewormed',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Not Sure')], default=3, verbose_name='是否已除虫'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='收养费'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='fur_length',
            field=models.IntegerField(blank=True, choices=[(1, 'Short'), (2, 'Medium'), (3, 'Long'), (0, 'Not Specified')], default=0, verbose_name='毛长'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='gender',
            field=models.IntegerField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Mixed, if profile represents group of pets')], default='3', verbose_name='动物性别'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='health',
            field=models.IntegerField(choices=[('0', 'Not Specified'), ('1', 'Healthy'), ('2', 'Minor Injury'), ('3', 'Serious Injury')], default=3, verbose_name='健康程度'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='maturity_size',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Specified'), (1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'Extra Large')], default=0, verbose_name='动物体型'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='pet_age',
            field=models.IntegerField(blank=True, default=0, verbose_name='动物年龄'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='pet_type',
            field=models.IntegerField(choices=[('1', 'Dog'), ('2', 'Cat')], default=None, verbose_name='动物类型'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='photo_amt',
            field=models.IntegerField(blank=True, default='None', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='primary_color',
            field=models.CharField(default=None, max_length=10, verbose_name='主要毛色'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='体重'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='secondary_color1',
            field=models.CharField(blank=True, default=None, max_length=10, verbose_name='次要毛色1'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='secondary_color2',
            field=models.CharField(blank=True, default=None, max_length=10, verbose_name='次要毛色2'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='sterilized',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Not Sure')], default=3, verbose_name='是否已消毒'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='vaccinated',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Not Sure')], default=3, verbose_name='是否接受疫苗'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='video_amt',
            field=models.IntegerField(blank=True, default='None', verbose_name='视频'),
        ),
    ]
