# Generated by Django 2.1.7 on 2019-03-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20190302_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_info',
            name='adoption_star',
            field=models.IntegerField(default=1, verbose_name='易收养指数'),
        ),
        migrations.AddField(
            model_name='pet_info',
            name='popularity_star',
            field=models.IntegerField(default=1, verbose_name='受欢迎指数'),
        ),
    ]
