# Generated by Django 2.1.7 on 2019-03-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20190311_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='dewormed',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Yes'), (2, 'No'), (3, 'Not Sure')], default=3, verbose_name='是否已除虫'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='fur_length',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Specified'), (1, 'Short'), (2, 'Medium'), (3, 'Long'), (0, 'Not Specified')], default=0, verbose_name='毛长'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Male'), (2, 'Female'), (3, 'Mixed, if profile represents group of pets')], default=3, verbose_name='动物性别'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Dog'), (2, 'Cat')], verbose_name='动物类型'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sterilized',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Yes'), (2, 'No'), (3, 'Not Sure')], default=3, verbose_name='是否已绝育'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccinated',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Yes'), (2, 'No'), (3, 'Not Sure')], default=3, verbose_name='是否接受疫苗'),
        ),
    ]
