# Generated by Django 2.1.7 on 2019-03-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20190306_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_info',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Mixed, if profile represents group of pets')], default=3, verbose_name='动物性别'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='health',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Healthy'), (2, 'Minor Injury'), (3, 'Serious Injury')], default=3, verbose_name='健康程度'),
        ),
    ]
