# Generated by Django 2.1.7 on 2019-03-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_auto_20190306_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_info',
            name='primary_breed',
            field=models.IntegerField(choices=[(1, 'Affenpinscher'), (2, 'Afghan Hound'), (3, 'Airedale Terrier')], default=None, max_length=200, verbose_name='主要血统'),
        ),
    ]
