# Generated by Django 2.1.7 on 2019-03-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20190306_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_info',
            name='secondary_breed',
            field=models.IntegerField(blank=True, choices=[(1, 'Affenpinscher'), (2, 'Afghan Hound'), (3, 'Airedale Terrier')], verbose_name='次要血统'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='secondary_color1',
            field=models.IntegerField(blank=True, choices=[(1, 'Black'), (2, 'Brown'), (3, 'Golden'), (4, 'Yellow'), (5, 'Cream'), (6, 'Gray'), (7, 'White')], verbose_name='次要毛色1'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='secondary_color2',
            field=models.IntegerField(blank=True, choices=[(1, 'Black'), (2, 'Brown'), (3, 'Golden'), (4, 'Yellow'), (5, 'Cream'), (6, 'Gray'), (7, 'White')], verbose_name='次要毛色2'),
        ),
    ]
