# Generated by Django 2.1.7 on 2019-03-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20190306_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_info',
            name='health',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Healthy'), (2, 'Minor Injury'), (3, 'Serious Injury')], default=0, verbose_name='健康程度'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='secondary_breed',
            field=models.IntegerField(blank=True, choices=[(1, 'Affenpinscher'), (2, 'Afghan Hound'), (3, 'Airedale Terrier')], default='None', verbose_name='次要血统'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='secondary_color1',
            field=models.IntegerField(blank=True, choices=[(1, 'Black'), (2, 'Brown'), (3, 'Golden'), (4, 'Yellow'), (5, 'Cream'), (6, 'Gray'), (7, 'White')], default='None', verbose_name='次要毛色1'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='secondary_color2',
            field=models.IntegerField(blank=True, choices=[(1, 'Black'), (2, 'Brown'), (3, 'Golden'), (4, 'Yellow'), (5, 'Cream'), (6, 'Gray'), (7, 'White')], default='None', verbose_name='次要毛色2'),
        ),
    ]
