# Generated by Django 2.1.7 on 2019-03-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_auto_20190306_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_info',
            name='photo_amt',
            field=models.IntegerField(default=0, verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='video_amt',
            field=models.IntegerField(default=0, verbose_name='视频'),
        ),
    ]
