# Generated by Django 2.1.7 on 2019-03-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_auto_20190307_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='breed',
            fields=[
                ('breed_id', models.AutoField(primary_key=True, serialize=False, verbose_name='血统ID')),
                ('breed_type', models.IntegerField(default=0, verbose_name='血统类型')),
                ('breed_name', models.CharField(default='', max_length=30, verbose_name='血统名称')),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False, verbose_name='颜色ID')),
                ('color_name', models.CharField(default='', max_length=30, verbose_name='颜色名称')),
            ],
        ),
        migrations.CreateModel(
            name='pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False, verbose_name='宠物ID')),
                ('primary_breed', models.IntegerField(choices=[(0, 'None'), (1, 'Affenpinscher'), (2, 'Afghan Hound'), (3, 'Airedale Terrier')], default=0, verbose_name='主要血统')),
                ('secondary_breed', models.IntegerField(choices=[(0, 'None'), (1, 'Affenpinscher'), (2, 'Afghan Hound'), (3, 'Airedale Terrier')], default=0, verbose_name='次要血统')),
                ('primary_color', models.IntegerField(choices=[(0, 'None'), (1, 'Black'), (2, 'Brown'), (3, 'Golden'), (4, 'Yellow'), (5, 'Cream'), (6, 'Gray'), (7, 'White')], default=0, verbose_name='主要毛色')),
                ('secondary_color1', models.IntegerField(choices=[(0, 'None'), (1, 'Black'), (2, 'Brown'), (3, 'Golden'), (4, 'Yellow'), (5, 'Cream'), (6, 'Gray'), (7, 'White')], default=0, verbose_name='次要毛色1')),
                ('secondary_color2', models.IntegerField(choices=[(0, 'None'), (1, 'Black'), (2, 'Brown'), (3, 'Golden'), (4, 'Yellow'), (5, 'Cream'), (6, 'Gray'), (7, 'White')], default=0, verbose_name='次要毛色2')),
                ('rescuer_name', models.CharField(blank=True, default=None, max_length=30, verbose_name='救助者姓名')),
                ('publisher_name', models.CharField(default=None, max_length=30, verbose_name='发布者姓名')),
                ('pet_type', models.IntegerField(choices=[(1, 'Dog'), (2, 'Cat')], verbose_name='动物类型')),
                ('pet_name', models.CharField(default=None, max_length=50, verbose_name='动物名称')),
                ('pet_age', models.IntegerField(blank=True, default=0, verbose_name='动物年龄')),
                ('maturity_size', models.IntegerField(blank=True, choices=[(0, 'Not Specified'), (1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'Extra Large')], default=0, verbose_name='动物体型')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Mixed, if profile represents group of pets')], default=3, verbose_name='动物性别')),
                ('fur_length', models.IntegerField(blank=True, choices=[(1, 'Short'), (2, 'Medium'), (3, 'Long'), (0, 'Not Specified')], default=0, verbose_name='毛长')),
                ('vaccinated', models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Not Sure')], default=3, verbose_name='是否接受疫苗')),
                ('dewormed', models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Not Sure')], default=3, verbose_name='是否已除虫')),
                ('sterilized', models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Not Sure')], default=3, verbose_name='是否已消毒')),
                ('health', models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Healthy'), (2, 'Minor Injury'), (3, 'Serious Injury')], default=0, verbose_name='健康程度')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='体重')),
                ('fee', models.IntegerField(default=0, verbose_name='收养费')),
                ('video_amt', models.IntegerField(default=0, verbose_name='视频')),
                ('photo_amt', models.IntegerField(default=0, verbose_name='照片')),
                ('description', models.CharField(default='发布者很懒，什么都没有说', max_length=500, verbose_name='描述')),
                ('adoption_speed', models.IntegerField(blank=True, default=0, verbose_name='被收养速率')),
                ('popularity_star', models.IntegerField(default=1, verbose_name='受欢迎指数')),
                ('adoption_star', models.IntegerField(default=1, verbose_name='易收养指数')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False, verbose_name='州ID')),
                ('state_name', models.CharField(default='', max_length=30, verbose_name='州名称')),
            ],
        ),
        migrations.DeleteModel(
            name='pet_info',
        ),
        migrations.AddField(
            model_name='pet',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.state', verbose_name='州位置'),
        ),
    ]
