# Generated by Django 2.1.7 on 2019-03-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_auto_20190307_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='breed',
        ),
        migrations.DeleteModel(
            name='color',
        ),
    ]
